{
 "title": "Jumpserver Audit Dashboard",
 "description": "This dashboard provides a comprehensive view of user activity and operational risk within the JumpServer environment. It is designed for security teams, auditors, and system administrators to monitor and analyze access behavior, session usage, command execution, and risk classification in real time.",
 "tags": [ "Jumpserver" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Login",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_login_logs\nFROM audits_userloginlog\nWHERE datetime BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "Total Operation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_operation_logs\nFROM audits_operatelog\nWHERE datetime BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "Password Changed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_password_change_logs\nFROM audits_passwordchangelog\nWHERE datetime BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "Online Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS online_sessions\nFROM terminal_session\nWHERE date_end IS NULL\n  AND date_start BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "Historical Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_historical_sessions\nFROM terminal_session\nWHERE date_end IS NOT NULL\n  AND date_start BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "File Transfer Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS file_transfer_count\nFROM audits_ftplog\nWHERE date_start BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  { "title": "Terminal Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  `user`,\n  SUBSTRING_INDEX(`asset`, '(', 1) AS asset_name,\n  REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(`asset`, '(', -1), ')', 1), ')', '') AS asset_ip,\n  protocol,\n  date_start AS start_time,\n  date_end AS end_time\nFROM terminal_session\nWHERE date_start BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_start AS `Date Start`,\n  `user` AS `User`,\n  SUBSTRING_INDEX(`asset`, '(', 1) AS `Asset Name`,\n  REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(`asset`, '(', -1), ')', 1), ')', '') AS `Asset IP`,\n  protocol AS `Protocol`,\n  id AS `Session ID`\nFROM terminal_session\nWHERE date_end IS NULL\n  AND date_start BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  {
   "title": "Session History",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_start AS `Date Start`,\n  date_end AS `Date End`,\n  `user` AS `User`,\n  SUBSTRING_INDEX(`asset`, '(', 1) AS `Asset Name`,\n  REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(`asset`, '(', -1), ')', 1), ')', '') AS `Asset IP`,\n  protocol AS `Protocol`,\n  id AS `Session ID`\nFROM terminal_session\nWHERE date_end IS NOT NULL\n  AND date_start BETWEEN $__timeFrom() AND $__timeTo();\n"
    }
   ]
  },
  { "title": "Total Duration - Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "type": "barchart",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  `user` AS `User`,\n  ROUND(SUM(TIMESTAMPDIFF(SECOND, date_start, date_end))) AS `Total Duration`\nFROM terminal_session\nWHERE date_start BETWEEN $__timeFrom() AND $__timeTo()\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  `user` AS `User`,\n  ROUND(SUM(TIMESTAMPDIFF(SECOND, date_start, date_end))) AS `Total Duration`\nFROM terminal_session\nWHERE date_end IS NOT NULL\n  AND date_start BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY `User`\nORDER BY `Total Duration` DESC;\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  `user` AS `User`,\n  ROUND(SUM(TIMESTAMPDIFF(SECOND, date_start, date_end))) AS `Total Duration`\nFROM terminal_session\nWHERE date_end IS NOT NULL\n  AND date_start BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY `user`\nORDER BY `Total Duration` DESC;\n"
    }
   ]
  },
  { "title": "Total Duration - Assets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "type": "barchart",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUBSTRING_INDEX(`asset`, '(', 1) AS `Asset Name`,\n  REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(`asset`, '(', -1), ')', 1), ')', '') AS `Asset IP`,\n  ROUND(SUM(TIMESTAMPDIFF(SECOND, date_start, date_end))) AS `Total Duration`\nFROM terminal_session\nWHERE date_end IS NOT NULL\n  AND date_start BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY `Asset Name`, `Asset IP`\nORDER BY `Total Duration` DESC;\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUBSTRING_INDEX(`asset`, '(', 1) AS `Asset Name`,\n  REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(`asset`, '(', -1), ')', 1), ')', '') AS `Asset IP`,\n  ROUND(SUM(TIMESTAMPDIFF(SECOND, date_start, date_end))) AS `Total Duration`\nFROM terminal_session\nWHERE date_end IS NOT NULL\n  AND date_start BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY `Asset Name`, `Asset IP`\nORDER BY `Total Duration` DESC;\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUBSTRING_INDEX(`asset`, '(', 1) AS `Asset Name`,\n  REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(`asset`, '(', -1), ')', 1), ')', '') AS `Asset IP`,\n  ROUND(SUM(TIMESTAMPDIFF(SECOND, date_start, date_end))) AS `Total Duration`\nFROM terminal_session\nWHERE date_end IS NOT NULL\n  AND date_start BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY `Asset Name`, `Asset IP`\nORDER BY `Total Duration` DESC;\n"
    }
   ]
  },
  { "title": "Command History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT\n  FROM_UNIXTIME(`timestamp`) AS `Timestamp`,\n  `user` AS `User`,\n  SUBSTRING_INDEX(`asset`, '(', 1) AS `Asset Name`,\n  REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(`asset`, '(', -1), ')', 1), ')', '') AS `Asset IP`,\n  input AS `Command`,\n  CASE\n    WHEN risk_level = 0 THEN 'Accept'\n    WHEN risk_level = 1 THEN 'Prompt'\n    WHEN risk_level = 2 THEN 'Warning'\n    WHEN risk_level = 3 THEN 'Block'\n    WHEN risk_level = 4 THEN 'Blacklist'\n    WHEN risk_level = 5 THEN 'Dangerous'\n    ELSE 'Unknown'\n  END AS `Risk Level`,\n  session AS `Session ID`\nFROM terminal_command\nWHERE `timestamp` BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY `Timestamp` DESC;\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN risk_level = 0 THEN 'Accept'\n    WHEN risk_level = 1 THEN 'Prompt'\n    WHEN risk_level = 2 THEN 'Warning'\n    WHEN risk_level = 3 THEN 'Block'\n    WHEN risk_level = 4 THEN 'Blacklist'\n    WHEN risk_level = 5 THEN 'Dangerous'\n    ELSE 'Unknown'\n  END AS `Risk Level`,\n  COUNT(*) AS `Count`\nFROM terminal_command\nWHERE `timestamp` BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY `Risk Level`\nORDER BY `Count` DESC;\n"
    }
   ]
  }
 ]
}